INSERT INTO users (name, age) VALUES ('Dave', 30);
INSERT INTO users (name, age) VALUES ('Sam', 45);
INSERT INTO users (name, age) VALUES ('Jess', 37);
INSERT INTO users (name, age) VALUES ('Courtney', 20);
INSERT INTO users (name, age) VALUES ('Bob', 20);
INSERT INTO users (name, age) VALUES ('Linda', 21);
INSERT INTO users (name, age) VALUES ('Carrie', 33);
INSERT INTO users (name, age) VALUES ('Marina', 19);
INSERT INTO users (name, age) VALUES ('Zach', 20);
INSERT INTO users (name, age) VALUES ('Melissa', 15);
INSERT INTO users (name, age) VALUES ('Vick', 52);
INSERT INTO users (name, age) VALUES ('Eric', 30);
INSERT INTO users (name, age) VALUES ('Tom', 41);
INSERT INTO users (name, age) VALUES ('Melinda', 42);
INSERT INTO users (name, age) VALUES ('Suzanne', 272);
INSERT INTO users (name, age) VALUES ('Holly', 72);
INSERT INTO users (name, age) VALUES ('Erin', 33);
INSERT INTO users (name, age) VALUES ('Fred', 86);
INSERT INTO users (name, age) VALUES ('Bob', 17);
INSERT INTO users (name, age) VALUES ('Eddie', 40);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "08-24-2020", "08-24-2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "07-25-2020", "08-25-2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "06-24-2020", "08-24-2023");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "05-19-2020", "10-07-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "06-24-2019", "09-15-2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "08-14-2020", "07-25-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "03-28-2018", "05-12-2023");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "02-17-2017", "09-20-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "05-20-2020", "11-01-2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ghost Sticks', 'tech', 8000, "011-02-2020", "12-02-2021");

INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 5, 800);

